### ISSUE TITLE
Add google photos style sections with server side loading for large number of images

### ISSUE THREAD

**Issue by prabirshrestha** [igordanchenko/react-photo-album#104]
### Is your feature request related to a problem? Please describe.

Would like to scroll to specific segments by month/day/year similar to google photos when viewing large albums as infinite scroll is not enough.

### Describe the solution you'd like

It would be great if there was support for google photos style rendering which scales very well for large number of images.

References: 
* https://medium.com/google-design/google-photos-45b714dfbed1
* https://javascript.plainenglish.io/how-to-implement-google-photos-grid-in-javascript-6c294bcea001 with source code at https://github.com/shaileshpandit/scrubbable-photos-grid and demo at https://glitch.com/edit/#!/scrubbable-photos-grid?path=script.js%3A11%3A19

**Comment by igordanchenko** [comment]
Thank you for bringing up this use case. Unfortunately, this is not something that fits well into `react-photo-album`'s mission. `react-photo-album` provides a solid foundation that you can use to build application-specific UX (or even release a separate component specifically for this usage scenario)

Have you considered rendering each section with a separate `PhotoAlbum` component and implementing server-side data loading at the application level?
