### ISSUE TITLE
Render photos with unknown height and width

### ISSUE THREAD

**Issue by prabirshrestha** [igordanchenko/react-photo-album#105]
### Is your feature request related to a problem? Please describe.

Currently we requiring specifying image width and height but this means we need to calculate the width and height before hand. 

I'm working on a simple list directory api which only returns the list of filenames and would like to use this library without specifying width and height and let the library auto handle width and height.

### Describe the solution you'd like

Add flags to render photos without specifying width and height.

**Comment by igordanchenko** [comment]
This library requires image dimensions to calculate the photo gallery layout. The only way this library could potentially obtain image dimensions would be by preloading images on the client side. But that would be no different from your app doing the same thing.

**Comment by prabirshrestha** [comment]
If that is the case it is possible to set the width and height to be constant for example 100px and have the image scale appropriately instead of stretch? Currently it always seems to stretch.

Something like this for react-photo-album as well as lightbox. Seems like it could be possible with some sort of overrides in CSS.

![image](https://user-images.githubusercontent.com/287744/223266559-8c108472-01e6-4527-8261-952bf59d1313.png)

**Comment by igordanchenko** [comment]
Sure, you can pass some fake width and height values and set `object-fit` to `cover`.

```tsx
componentsProps={{ imageProps: { style: { objectFit: "cover" } } }}
```

But if that's the layout you want, maybe you do not need this library in the first place. CSS grid layout would be a much more straightforward option.
