### ISSUE TITLE
Unable to render PhotoAlbum component after installation and setup - React v17.0.2

### ISSUE THREAD

**Issue by naemtl** [igordanchenko/react-photo-album#124]
### Describe the bug

Hi, I'm trying to use your PhotoAlbum and Lightbox libs together to create an image gallery with lightbox functionality in my application. After installing your libs, it seems I'm unable to render anything coming from them. This is probably something I'm doing wrong, but I can't figure out what that is. I've also tried copying a simple example from your documentation to see if I can isolate the issue, but the problem persists. 

### Expected behavior

I expect the code to render. I don't receive any console errors though or anything to help me decipher what is going wrong.

### How to reproduce

Here's my code: 

```
import LightboxGallery from "../../components/LightboxGallery/LightboxGallery";

import popOneImg from "../../assets/images/pop-1.png";
import popTwoImg from "../../assets/images/pop-2.png";
import popThreeImg from "../../assets/images/pop-3.png";
import popFourImg from "../../assets/images/pop-4.png";
import popFiveImg from "../../assets/images/pop-5.png";
import popSixImg from "../../assets/images/pop-6.png";
import popSevenImg from "../../assets/images/pop-7.png";

import "./Principle.scss";

const LightboxGalleryContainer = () => (
  <div className="principle__images">
    <img className="principle__image" alt="Gerard" src={popOneImg} />
    <img className="principle__image" alt="Gerard" src={popTwoImg} />
    <img className="principle__image" alt="Gerard" src={popThreeImg} />
    <img className="principle__image" alt="Gerard" src={popFourImg} />
    <img className="principle__image" alt="Gerard" src={popFiveImg} />
    <img className="principle__image" alt="Gerard" src={popSixImg} />
    <img
      className="principle__image principle__image--seven"
      alt="Gerard"
      src={popSevenImg}
    />
  </div>
);

const Principle = () => {
  return (
    <div className="principle">
      {/* ... */}
        <LightboxGallery
          albumContainer={LightboxGalleryContainer}
          lightboxSlides={[
            { src: popOneImg },
            { src: popTwoImg },
            { src: popThreeImg },
            { src: popFourImg },
            { src: popFiveImg },
            { src: popSixImg },
            { src: popSevenImg },
          ]}
          />
      {/* ... */}
    </div>
  );
};

export default Principle;
```

The LightboxGallery component which I've made to reuse a couple times in my app: 

```
import React, { useState } from "react";
import PhotoAlbum from "react-photo-album";
import Lightbox from "yet-another-react-lightbox";
import "yet-another-react-lightbox/styles.css";

import "./LightboxGallery.scss";

const LightboxGallery = ({ albumContainer, lightboxSlides }) => {
  const [index, setIndex] = useState(-1);

  return (
    <>
      <PhotoAlbum
        renderContainer={albumContainer}
        targetRowHeight={150}
        onClick={({ index: current }) => setIndex(current)}
      />

      <Lightbox
        index={index}
        slides={lightboxSlides}
        open={index >= 0}
        close={() => setIndex(-1)}
      />
    </>
  );
};

export default LightboxGallery;
```

**Comment by igordanchenko** [comment]
Please review the [documentation](https://react-photo-album.com/documentation) and [minimal setup example](https://react-photo-album.com/#MinimalSetupExample). You are not passing the required parameters, so the result is not surprising.

**Comment by naemtl** [comment]
@igordanchenko I apologize, you're correct that I missed some details in the documentation. For example, I didn't realize you still need to pass the `photos` prop if you're also passing a `renderContainer` prop to `PhotoAlbum`. I may have one last question for you but I'll try to figure it out on my own for a little while first.

**Comment by igordanchenko** [comment]
Actually, both `layout` and `photos` props are required. Also I'm not sure you want to use custom `renderContainer` in this case. I'd suggest you start without custom render functions and work from there.

**Comment by naemtl** [comment]
Everything works now, thanks again, and apologies for the useless bug entry!

**Comment by igordanchenko** [comment]
I remember seeing similar error in either Chrome or Safari long time ago, but it was a [non-issue](https://stackoverflow.com/a/50387233/21872981) and could be safely ignored. But the fact that you have a stack trace in your error message, makes me suspect you may be using some sort of ResizeObserver polyfill in your project. Please open new discussion and provide minimal reproducible example if you require further assistance.
