### ISSUE TITLE
ReferenceError: useForkRef is not defined

### ISSUE THREAD

**Issue by NiclasHaderer** [igordanchenko/react-photo-album#125]
### Describe the bug

The demo website crashes when trying to switch the layout (https://react-photo-album.com/examples/playground)

### Expected behavior

Does not crash

### How to reproduce

Try to switch layout in demo

### Screenshots / Logs

[Screencast from 21.08.2023 15:18:47.webm](https://github.com/igordanchenko/react-photo-album/assets/109728711/793edf2c-aab8-4b36-8302-d4035730a802)

**Comment by igordanchenko** [comment]
Thank you for reporting this issue! This is now fixed.

**Comment by NiclasHaderer** [comment]
Thanks for your quick fix!
