### ISSUE TITLE
Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by gabrielvieiraes** [igordanchenko/react-photo-album#144]
### Describe the bug

Failed to compile.

> ./node_modules/react-photo-album/dist/index.mjs
> Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)

### Expected behavior

Project does not compile when I try to use PhotoAlbum

### How to reproduce

```jsx
<PhotoAlbum
  layout="rows"
  photos={slides}
  targetRowHeight={150}
  onClick={({ index: current }) => setIndex(current)}
/>

<Lightbox index={index} slides={slides} open={index >= 0} close={() => setIndex(-1)} />
```

**Comment by igordanchenko** [comment]
Your ticket does not provide sufficient details to troubleshoot. Why don't you start by describing your environment? (Node version, React version, framework / build toolchain, etc.)

**Comment by gabrielvieiraes** [comment]
Node - v16.20.0
React - ^16.12.0
craco/craco - ^5.6.2
Mantine -  6.0.19

**Comment by igordanchenko** [comment]
And what is your `react-scripts` (CRA) version?
