### ISSUE TITLE
Ability to make an image full-width

### ISSUE THREAD

**Issue by canastro** [igordanchenko/react-photo-album#163]
### Is your feature request related to a problem? Please describe.

I have a Rows layout, but I want a particular image to standout and completely fill the entire row.

### Describe the solution you'd like

The easiest way from a consumer standpoint would be to have this as a configuration in the "Photo"

**Comment by igordanchenko** [comment]
While this isn't something supported by this library's layout algorithm, there is a straightforward way to implement the desired layout by stacking multiple photo albums on top of each other:

```jsx
<>
  <PhotoAlbum layout="rows" spacing={10} photos={photos.slice(0, 3)} />
  <PhotoAlbum
    layout="rows"
    photos={photos.slice(3, 4)}
    componentsProps={{ containerProps: { style: { margin: "10px 0" } } }}
  />
  <PhotoAlbum layout="rows" spacing={10} photos={photos.slice(4)} />
</>
```

Doe this address your use case?

I'm not keen on implementing this as a library feature at this point, as I'm not sure how well such layouts would look on various viewport sizes (specifically, desktop vs mobile). Please feel free to share some screenshots of what you are building.

**Comment by canastro** [comment]
It works perfectly, thank you!

https://github.com/igordanchenko/react-photo-album/assets/1267623/f6f0ecd0-3f8a-4ed1-88f9-43ed34317575
