### ISSUE TITLE
v3 Breaking Changes

### ISSUE THREAD

**Issue by igordanchenko** [igordanchenko/react-photo-album#172]
# v3 Breaking Changes

Release 3.0 comes with a number of breaking changes. Please review the items applicable in your case.

## Photo album component and CSS stylesheet

v3 provides 4 different components depending on the layout you intend to use. Each component comes with its own CSS stylesheet. **CSS stylesheet is not optional!**

### Rows layout:

```tsx
import { RowsPhotoAlbum } from "react-photo-album";
import "react-photo-album/rows.css";
```

### Columns layout:

```tsx
import { ColumnsPhotoAlbum } from "react-photo-album";
import "react-photo-album/columns.css";
```

### Masonry layout:

```tsx
import { MasonryPhotoAlbum } from "react-photo-album";
import "react-photo-album/masonry.css";
```

### 3-in-1:

If you use more than one layout in our app, you may opt for the aggregate component, which bundles all three layouts.

```tsx
import PhotoAlbum from "react-photo-album";
import "react-photo-album/styles.css";
```

## React version

React 18 is the minimum supported React version.

## Node version

Node 18 is the minimum supported Node version.

## ESM

The library is now ESM-only.

## renderContainer

`renderContainer` is no longer supported. Use `render.container` instead.

## renderRowContainer

`renderRowContainer` is no longer supported. Use `render.track` instead.

## renderColumnContainer

`renderColumnContainer` is no longer supported. Use `render.track` instead.

## renderPhoto

`renderPhoto` is no longer supported. Use `render.image`, `render.wrapper`, `render.link`, `render.button` or `render.photo` instead.

## componentsProps.containerProps

`componentsProps.containerProps` is no longer supported. Use `componentsProps.container` instead.

## componentsProps.rowContainerProps

`componentsProps.rowContainerProps` is no longer supported. Use `componentsProps.track` instead.

## componentsProps.columnContainerProps

`componentsProps.columnContainerProps` is no longer supported. Use `componentsProps.track` instead.

## componentsProps.imageProps

`componentsProps.imageProps` is no longer supported. Use `componentsProps.image`, `componentsProps.wrapper`, `componentsProps.link` or `componentsProps.button` instead.

## Photo `images` prop

The deprecated `images` prop is no longer supported. Use `srcSet` instead.

**Comment by xucongli1989** [comment]
Thanks for your product! Have you considered using virtual scrolling to improve performance? For example: `react-window`?

**Comment by igordanchenko** [comment]
I've been thinking of implementing something along these lines for the upcoming [InfiniteScroll](https://next.react-photo-album.com/documentation#InfiniteScroll) component but not for the core library itself. Can you share an example showing performance issues that you see?

p.s. Do you mind re-posting your question in the [Discussions](https://github.com/igordanchenko/react-photo-album/discussions) to continue this conversation over there?
