### ISSUE TITLE
onError callback api for image

### ISSUE THREAD

**Issue by leopku** [igordanchenko/react-photo-album#183]
### Is your feature request related to a problem? Please describe.

I need change src attribute of img when error occurred. But there's no onError callback api for this awesome library.

I had try renderPhoto(yep, I'm using 2.4.x currently), but I can't make onClick work(I will submit another issue about this).

### Describe the solution you'd like

something like onError of img tag, so I can change image source in it.

```js
<PhotoAlbum layout="masonry" photos={thumbs} onImgError={(evt) => evt.src = 'another_url' } />
```

**Comment by igordanchenko** [comment]
You can specify the `onError` callback through the `componentsProps.imageProps`:

```jsx
componentsProps={{
  imageProps: {
    onError: (event) => {
      const { src } = event.target as HTMLImageElement;
      console.log("Failed to load", src);
    },
  },
}}
```

**Comment by leopku** [comment]
It works.
Thanks a lot.

**Comment by igordanchenko** [comment]
The `onError` prop accepts a functional callback, but you are setting it to an object.
