### ISSUE TITLE
onError callback prop

### ISSUE THREAD

**Issue by averwhy** [igordanchenko/react-photo-album#186]
### Is your feature request related to a problem? Please describe.

I am looking a way to handle errors when images don't load (cloudflare moment)

### Describe the solution you'd like

an onError callback function would be really helpful to do so, that way i know when to have a error message appear or something like that

### Describe alternatives you've considered

I've considered modifying this libraries source to do so but I will not because of time constraints

**Comment by igordanchenko** [comment]
Duplicate #183
