### ISSUE TITLE
Add react@19 as a peer dependency

### ISSUE THREAD

**Issue by canastro** [igordanchenko/react-photo-album#187]
### Is your feature request related to a problem? Please describe.

Next just released a stable version of next@15 which depends on the RC of react@19

### Describe the solution you'd like

Is it possible to bump the react / react-dom peer deps to react@19 rc?

**Comment by igordanchenko** [comment]
Can you describe the issue you are facing?

This library uses react peer dependency range `>=18`, so react@19 is already included in the peer dependency range.

**Comment by canastro** [comment]
Oh I didnt notcied it was `>=` I automatically read it as `^`.

I'm getting this weird error message on `pnpm i`:

```
├─┬ react-photo-album 3.0.2
│ └── ✕ unmet peer @types/react@npm:types-react@19.0.0-rc.1: found 19.0.0-rc.1
```

Anyway, seems to be a problem on my end, so I'll close this PR. Sorry for the confusion.

**Comment by igordanchenko** [comment]
FWIW the error you quoted above is related to `@types/react`, not the `react` RC. You may need to check `overrides` in your `package.json`.
