### ISSUE TITLE
How to force certain number of columns for the masonry layout?

### ISSUE THREAD

**Issue by jaycincotta** [igordanchenko/react-photo-album#62]
### Is your feature request related to a problem? Please describe.

I'm trying to migrate from react-photo-gallery to react-photo-album.  The number of columns (1-3) is decided based on the width of the client.  An issue I have with react-photo-gallery is that I want to specify internal margins without having any margin added to external edges of the album.  I could switch to react-photo-album, but on a quick review of the doc, I didn't see an equivalent columns property.

### Describe the solution you'd like

I'm hoping for an easy upgrade path from react-photo-gallery to react-photo-album.  API compatibility would make the upgrade trivial.

### Describe alternatives you've considered

I don't see negative margins as a viable workaround for my use case because I'd need to stretch the entire album, not just translate it.

### Additional context

Here's a [sandbox](https://codesandbox.io/s/gesturesoflove-v4-lk29qd?file=/src/ImageGallery/components/ImageMosaic/components/GridImage.js) of my project.  I want to eliminate the extra margin [highlighted in red](https://photos.app.goo.gl/ZuM8qJ8HBJcmKB8n7) and retain the semantics of the number of columns varying between -3 depending on the client device.

**Comment by igordanchenko** [comment]
@jaycincotta, I believe the prop you are looking for is `spacing` - https://react-photo-album.com/documentation

> Spacing between images (similar to CSS grid gap)

You may also find the following write up useful - https://github.com/igordanchenko/react-photo-album/discussions/55. While I haven't had a chance to put a comprehensive migration doc together, that post covers the major differences with react-photo-gallery.

**Comment by igordanchenko** [comment]
I'll take a closer look at your codesandbox, but the first show stopper I noticed so far is the React version. You are using 16.13.1, but the minimum version `react-photo-album` is compatible with is 16.14.0

**Comment by igordanchenko** [comment]
Have a look at the forked sandbox - https://codesandbox.io/s/gesturesoflove-v4-forked-zr6x8k?file=/src/ImageGallery/components/ImageMosaic/index.js

**Comment by jaycincotta** [comment]
OMG! That looks fantastic!  Thank you so much, Igor!  I was bracing myself for hours of debugging and you did it in minutes.  You're a complete rock star.  Wow, wow, wow.  Can't thank you enough, this is just terrific.

**Comment by jaycincotta** [comment]
Oh, one last thing...  I was so impressed with the layout I didn't notice at first that the captions are lost,  Is there a mechanism to associate a caption with each photo?

**Comment by igordanchenko** [comment]
I had to comment out your custom `renderImage` function since it needs to be updated. What you currently see is rendered via the default render photo function. Give me a few to make the edits. I'll ping you when I'm done.

**Comment by igordanchenko** [comment]
Take a look now - https://codesandbox.io/s/gesturesoflove-v4-forked-zr6x8k?file=/src/ImageGallery/components/ImageMosaic/components/GridImage.js

**Comment by jaycincotta** [comment]
Yes, that is perfect.  It handles the resizing correctly including edge cases where the captions wrap.  And adding shadows on the paintings is a nice touch.  Let me know if I can do anything for you such as writing a testimonial for your awesome library.

**Comment by igordanchenko** [comment]
Please consider giving this repo a star here on GitHub if you like the library 🙌
