### ISSUE TITLE
Overhaul package bundle

### ISSUE THREAD

**Issue by igordanchenko** [igordanchenko/react-photo-album#63]
### Is your feature request related to a problem? Please describe.

`react-photo-album` currently bundles the following assets within its package:
- `esm` bundle (44K)
- `cjs` bundle (16K)
- `umd` bundle (16K)
- TS declarations (9K)
- source maps (243K)

UMD bundle is not in demand since 100% of current library consumers use bundlers in their respective projects (CRA, Next.js, Gatsby, custom webpack bundle, etc.). Also bundlers do not need the code to be excessively transpiled as it is today, which also presents an opportunity to remove source maps.

We can substantially reduce overall package size by eliminating UMD bundle and source maps.

### Describe the solution you'd like

- decommission UMD bundle (hopefully for good this time)
- remove `babel` from build pipeline
- transpile the code down to `ES2018`
- remove source maps since the code will no loner be "obfuscated" by excessive transpilation
- remove comments from `esm` and `cjs` bundles
- don't uglify `cjs` bundle

**Comment by igordanchenko** [comment]
Overall npm package size reduced from 347 kB down to 80.5 kB

https://www.npmjs.com/package/react-photo-album/v/1.11.1
https://www.npmjs.com/package/react-photo-album/v/1.12

Minzipped bundle size reduced from 5.1 kB down to 4.5 kB

![Screen Shot 2022-04-01 at 7 18 29 PM](https://user-images.githubusercontent.com/64441155/161353638-e31d31ba-ad54-418b-9958-1f28113e923f.png)

**Comment by Georg-Git** [comment]
I am very happy to find Your library!

But now I become aware that version 1.11.1 is the last one for me:
"UMD bundle is not in demand since 100% of current library consumers ..."

So - 100% is not correct - here is at least one consumer of the UMD bundle! 😎😎

Any chance for Updates of the file index.umd.js?

**Comment by igordanchenko** [comment]
> So - 100% is not correct - here is at least one consumer of the UMD bundle! 😎😎

Well, that statement was 100% accurate at that time based on all public GitHub repos using the library 😉 

Can you describe you environment that requires UMD bundle?

**Comment by Georg-Git** [comment]
I don't have a build environment.
Just take your cdn example with the js files, knit some hml, js and php code around it for my own photo gallery.

**Comment by igordanchenko** [comment]
Ah, I see. Unfortunately, there is no way to turn back time, and UMD is already a matter of the past. Let's move on to ESM bundle!

Here is a working snippet using the ESM bundle:

```html
<div id="root"></div>

<script type="module">
    import React from "https://esm.sh/react@18";
    import { createRoot } from "https://esm.sh/react-dom@18/client";
    import { PhotoAlbum } from "https://esm.sh/react-photo-album@1";

    createRoot(document.getElementById("root"))
        .render(React.createElement(PhotoAlbum, { layout: "rows", photos }));
</script>
```

Please let me know if this works for you.

**Comment by Georg-Git** [comment]
Thank You very much!
Yes - esm JS fits to my target browsers.

But at the end I want all files on my own server - or running also in offline mode.

So I downloaded the files and changed:
```
import React from "./js-esm/react.js";
import { createRoot } from "./js-esm/react-dom.js";
import { PhotoAlbum } from "./js-esm/react-photo-album.js";
```

But in Your file "react-photo-album.js" are two other imports:

```
/* esm.sh - esbuild bundle(react-photo-album@1.15.0) es2022 production */
import {jsx as y, Fragment as R} from "/v87/react@18.2.0/es2022/jsx-runtime.js";
import {useLayoutEffect as F, useEffect as H, useRef as M, useMemo as B, useState as z, useCallback as D} from "/v87/react@18.2.0/es2022/react.js";
```

The directories of these files does not fit to my use case.

**Comment by igordanchenko** [comment]
Can you try downloading https://esm.sh/v87/react@18.2.0/es2022/jsx-runtime.js as "./js-esm/jsx-runtime.js" and changing imports to:

```
import {jsx as y, Fragment as R} from "./js-esm/jsx-runtime.js";
import {useLayoutEffect as F, useEffect as H, useRef as M, useMemo as B, useState as z, useCallback as D} from "./js-esm/react.js";
```

**Comment by Georg-Git** [comment]
Current status:

1.) use case import from "https://esm.sh/...."
Your proposal was running out of the box.
But of course it needs some time until the browser has collected all the files from esm.sh.
Nevertheless worthy to become part of Your examples in Your package.

2.) use case import from own server "./js-esm/..."
To make this work 6 js files have to be downloaded manuallly.
And in all files some directory pathes have to be edited manually.
Nevertheless - at the end the photo album is running smoothly with all files on my own server.

3.) use case offline on local file system:
When opening the photo album from point 2 on my local file system the browser blocked importing module e.g.:
"Access to script at 'file:///C:/photoalbum/js-esm/react.js' from origin 'null' has been blocked by CORS policy"

=> Better to spent my time now on Your last proposal - I will keep You informed 😎

**Comment by igordanchenko** [comment]
> "Access to script at 'file:///C:/photoalbum/js-esm/react.js' from origin 'null' has been blocked by CORS policy"

Can you try adding `crossorigin` attribute to the script tag?

**Comment by Georg-Git** [comment]
I succeeded in building the file "react-photo-album-standalone.js"!

=> in both use cases the photo album is now running without any problems: 
- from my server and 
- offline on local file

I am impressed: 
all Your proposals in Your quick responces were working out of the box.

I want to kiss Your feet and send to You frankincense and myrrh 🤣😉
Thank You very much - You make my day 👍
