### ISSUE TITLE
Cannot build the program

### ISSUE THREAD

**Issue by lertsoft** [igordanchenko/react-photo-album#65]
### Describe the bug

The app would work and behave as it should when it is on dev mode but any time I try to run the production version it gives me the error and I've try some solutions but none of them since to work...

One of the solutions that I tried was forcing explicitly telling typescript/next the type of the variable but I also got an error with that solution but without any helpful ways to debug myself.

### Expected behavior

The build of the website succeeds. 

### How to reproduce

nextJsImage.tsx file

```
import React from 'react';

import Image from 'next/image';
import { PhotoProps } from 'react-photo-album';

type NextJsImageProps = PhotoProps & {
  wrapperProps?: React.HTMLAttributes<HTMLDivElement>;
};

const NextJsImage = ({ photo, imageProps, wrapperProps }: NextJsImageProps) => {
  const { width, height } = photo;
  const { src, alt, title, style, sizes, className, onClick } = imageProps;
  const { style: wrapperStyle, ...restWrapperProps } = wrapperProps ?? {};

  return (
    <div
      style={{
        width: style.width,
        padding: style.padding,
        marginBottom: style.marginBottom,
        ...wrapperStyle,
      }}
      {...restWrapperProps}
    >
      <Image
        src={src}
        alt={alt}
        title={title}
        sizes={sizes}
        width={width}
        height={height}
        className={className}
        onClick={onClick}
      />
    </div>
  );
};

export default NextJsImage;

```
### Screenshots / Logs

<img width="1186" alt="Screen Shot 2022-04-06 at 6 41 50 PM" src="https://user-images.githubusercontent.com/28693094/162084573-5b17b39b-6d7c-4f3f-a512-d352cf17f497.png">

### Additional context

I am on a MacBook Pro m1 pro and These are my dependancies: 

 "tailwindcss": "^3.0.23",
    "typescript": "^4.6.2"
    "next": "^12.1.0",
    "next-seo": "^5.2.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-photo-album": "^1.11.1",
    "react-swipeable": "^6.2.1",
    "styled-components": "^5.3.5"

**Comment by igordanchenko** [comment]
@lertsoft, can you point me a to a sample project reproducing this issue? A GitHub repo or Codesandbox demo would be great.

Based on the screenshot you provided, it's not a type checking error but rather the NextJsImage render function receiving an undefined photo object.

**Comment by lertsoft** [comment]
Hey I find out what the issue was... I just had the function mixed up with the pages which I didn't know was forbidden by next.
