### ISSUE TITLE
Accept a prop that allows forcing the number of containers

### ISSUE THREAD

**Issue by JaredMichel** [igordanchenko/react-photo-album#72]
### Is your feature request related to a problem? Please describe.

Say I want a 4 column masonry layout. Right now if I have 2 images, that layout will expand the width of the images to 50% rather than 25% due to https://github.com/igordanchenko/react-photo-album/blob/main/src/layouts/masonry.ts#L16

I would like to be able to force the 4 column layout even though I don't have at least 4 images. This would be nice to have in the scenario, for example, where I have a feed of items each with a photo album and variable # of images where I'd like all of the photo album layouts to look uniform.

### Describe the solution you'd like

An additional prop that ignores the default `Math.min` behavior of column # calculation

### Describe alternatives you've considered

An alternate solution I've considered is changing the width of the wrapping `div` that wraps the photo album component. For example, in my example using a wrapping width of 50% would achieve what I'd like, but this gets unnecessarily complicated because of the responsive number of columns my photo album uses at different screen sizes. So I have to observe the width of my wrapping component and dynamically update the wrapper's width when this would be simpler if it were built into the library.

**Comment by igordanchenko** [comment]
Hi @JaredMichel,

Thank you for reporting this issue and describing the use case. I'll work on it next week, but in the meantime, here is a simple workaround you can use to achieve the desired layout:

```
<PhotoAlbum
    photos={
        photos.length > 0 && photos.length < 4
            ? [
                  ...photos,
                  ...Array(4 - photos.length).fill({
                      src: "data:image/gif;base64,R0lGODdhAQABAJEAAAAAAP///wAAAAAAACH5BAkAAAIALAAAAAABAAEAAAICVAEAOw==",
                      width: photos[0].width,
                      height: photos[0].height,
                  }),
              ]
            : photos
    }
    layout="masonry"
    columns={4}
/>
```

**Comment by igordanchenko** [comment]
You can now use `columnConstraints.minColumns` prop to achieve the desired behavior.

```
<PhotoAlbum 
  photos={photos} 
  layout="masonry" 
  columns={4} 
  columnConstraints={{ minColumns: 4 }} 
/>
```

**Comment by korneSt** [comment]
Hi @igordanchenko, is it possible to work the same way but for `rows` layout?

**Comment by igordanchenko** [comment]
@korneSt, can you describe the layout you are trying to achieve? I'm not sure how a similar feature would work in the `rows` layout since `PhotoAlbum` has a fixed width that is determined by its parent container.

**Comment by igordanchenko** [comment]
Please see if the following is what you are trying to achieve. 

```jsx
<PhotoAlbum
  photos={photos}
  layout="rows"
  targetRowHeight={(w) =>
    (targetRows * w) /
    photos.reduce((acc, { width, height }) => acc + width / height, 0)
  }
/>
```

Demo - https://codesandbox.io/s/react-photo-album-72-722kzb?file=/src/App.tsx

However, this approach won't work in a generic case. However, this approach won't work in a generic case unless you implement an upper bound on the number of photos.

**Comment by korneSt** [comment]
@igordanchenko Thanks for the replay. I was actually talking about the same behavior as in https://github.com/igordanchenko/react-photo-album/discussions/67. So when there are less items in the row they don't grow. As I understood it can be done in user land. 

Thanks for the great library.
