### ISSUE TITLE
React-photo-album rendering problem.

### ISSUE THREAD

**Issue by geohuz** [igordanchenko/react-photo-album#73]
### Describe the bug

In my following code, it renders only in columns layout, the rows and masonry renders blank page (with no child items) and there is no error. Even in columns layout the rendering looks weird.

may be the algorithm returns empty result for my case?

```jsx
import PhotoAlbum from 'react-photo-album'

const breakpoints = [1080, 640, 384, 256, 128, 96, 64, 48];

var raw_photos = [
  {
    src: "/DSC04835.jpeg",
    width: 2280,
    height: 1901
  },
  { 
    src: "/DSC04841.jpeg",
    width: 4302,
    height: 3718
  },
  { 
    src: "/DSC05860.jpeg",
    width: 4000,
    height: 3986
  },
  { 
    src: "/DSC07344.jpeg",
    width: 6000,
    height: 4000
  },
  { src: "/DSC07350.jpeg",
    width: 6000,
    height: 4000
  },
  { src: "/DSC07353.jpeg",
    width: 4009,
    hegith: 3257
  },
  { src: "/DSC07362.jpeg",
    width: 5828,
    height: 4000
  },
  { src: "/DSC07364.jpeg",
    width: 4025,
    height: 3988
  },
  { src: "/DSC07367.jpeg",
    width: 4044,
    height: 3826
  },
]

const photos = raw_photos.map(photo=> ({
  src: photo.src,
  width: photo.width,
  images: breakpoints.map(breakpoint=> {
    const height = Math.round((photo.height / photo.width) * breakpoint);
    return {
        src: photo.src,
        width: breakpoint,
        height,
    };
  })
}))
function App() {

  return (
    <div>
      <PhotoAlbum layout="rows" photos={photos} />
    </div>
  );
}

export default App;
```

### Expected behavior

It should render in all cases.

### How to reproduce

May be use something like react-image-placeholder to reproduce. The image files are too large.

### Screenshots / Logs

The columns layout rendering screenshot:
<img width="749" alt="Screen Shot 2022-07-13 at 19 36 17" src="https://user-images.githubusercontent.com/730770/178725092-0bc12c80-041b-4b66-bcaa-db56d1ffccdd.png">

**Comment by igordanchenko** [comment]
You are passing an invalid `photos` object.

1) All photos are missing the top-level `height` property
2) There is a typo in `DSC07353.jpeg` photo `height` property which is spelled as `hegith` (which results in all kinds of NaN's in the algorithm)

**Comment by igordanchenko** [comment]
For future reference: to create a repro without uploading actual images, images can be replaced with a simple placeholder.

```
src: "data:image/gif;base64,R0lGODdhAQABAJEAAAAAAB8fH////wAAACH5BAkAAAMALAAAAAABAAEAAAICTAEAOw=="
```

**Comment by geohuz** [comment]
Oh, my bad! correct the typo fixed my problem!
