### ISSUE TITLE
A style like facebook photo album

### ISSUE THREAD

**Issue by geohuz** [igordanchenko/react-photo-album#74]
### Is your feature request related to a problem? Please describe.

This is awesome lib and every thing works fine, it would be perfect that we can have an option that mimics facebook "+x" style.

### Describe the solution you'd like

Have an option which sets the number of photos displayed in the layout, then we have "+x (1,2,3...)" number displayed in the last photo, which is remainning photos need to be displayed, when viewer click the last one we switch to lightbox mode.

**Comment by igordanchenko** [comment]
I'm afraid this is outside the scope of this library, and won't be implemented as requested. 

Features of this kind can and should be implemented by app developers. You can implement this feature via a custom `renderPhoto` function by wrapping a photo in a container and rendering the desired "+x" label. 

However, there is currently no way to use both default photo renderer and custom `renderPhoto` just for specific photo(s). I'll release this feature. I will keep this ticket open till this part is implemented.

**Comment by Georg-Git** [comment]
Right now I'm thinking about a similar challenge.

I want to use this photo album also with subdirectories.
But how to display a subfolder in such a gallery?

In Nextcloud they put the first 4 photos of the subfolder together to one picture in the gallery.
And then they display a folder icon and the name of the directory as an overlay on this special picture.

I can follow Igor's reasoning about the scope of this library.

So the main question is how to flag the need for special rendering e.g. for:
- picture of a directory with other photos
- last picture of gallery for the remaining photos
- picture for photo groups / paging
- etc.


Right now the variable photos includes for every picture the following properties:
- src (URL)
- width
- height


So I suggest to add to this list another property:
- name of extended or custom renderer

**Comment by igordanchenko** [comment]
Here is how you can render a placeholder in the current photo album version - https://codesandbox.io/s/react-photo-album-74-t8nxtk?file=/src/App.tsx

An overlay can be rendered in a similar fashion.

**Comment by Georg-Git** [comment]
Ah - that would help - at least the react people. 😎

But do You remember:
I am the old fashioned user using Your library in a javascript environment without the letter 'x':

```
<script src="./react-photo-album-standalone.js"></script>
<script>
    RenderPhotoAlbum("#root", { layout: "rows", photos })
</script>
```
https://github.com/igordanchenko/react-photo-album/issues/63#issuecomment-1185055725

Is there a chance for the elderly to get a hook or callback function?
😎

**Comment by igordanchenko** [comment]
@geohuz, I just published v1.16.0, which makes wrapping a specific photo in a custom wrapper much more convenient.

Take a look at the following example. I believe that's the feature you were asking for.

https://codesandbox.io/s/react-photo-album-74-1-bjey7j?file=/src/App.tsx

**Comment by igordanchenko** [comment]
@Georg-Git,

> Is there a chance for the elderly to get a hook or callback function?

I'm not sure what you mean by this, but please feel free to open a new ticket if you are facing an issue with the library.

**Comment by geohuz** [comment]
Hi @igordanchenko! sorry for the late reply, thanks for the solution and it looks cool!
