### ISSUE TITLE
Support for video

### ISSUE THREAD

**Issue by Cgadal** [igordanchenko/react-photo-album#77]
### Is your feature request related to a problem? Please describe.

Awesome work, thank you very much ! It would be very nice if could include video to gallery as well.

### Describe the solution you'd like

Including video along images inside the gallery.

**Comment by igordanchenko** [comment]
You can render custom gallery elements with [renderPhoto](https://react-photo-album.com/documentation#RenderPhoto).

Example: https://codesandbox.io/s/react-photo-album-77-l5erug
