### ISSUE TITLE
Set minimum aspect ratio for image

### ISSUE THREAD

**Issue by marlenekoh** [igordanchenko/react-photo-album#89]
### Is your feature request related to a problem? Please describe.

Hi, is it possible to set a minimum aspect ratio? I am using the rows layout with a custom renderer.

in my example, the caption will wrap because it's too long. I want to put the username and date in the same line (expected 1st photo on the left)
![image](https://user-images.githubusercontent.com/28558150/210130058-d7ce3319-2543-4c3b-8b35-26b5c4bb64e3.png)

Thank you :)

### Describe the solution you'd like

set a minimum aspect ratio so that no images are too narrow.

e.g. for google photos, they add a white background to the image (see middle iphone image) to maintain aspect ratio
![image](https://user-images.githubusercontent.com/28558150/210130076-d2e6f78a-abfa-41cc-84b3-7d872f7c0291.png)

### Describe alternatives you've considered

Have looked at react-aspect-ratio (https://www.npmjs.com/package/react-aspect-ratio) but not sure how to get the width and height of the scaled image to pass into the photos prop.

**Comment by igordanchenko** [comment]
Thank you for bringing up this interesting use case! Here is how you can implement a minimum aspect ratio in the photo gallery - https://codesandbox.io/s/react-photo-album-89-2hw0lx
