### ISSUE TITLE
Extending RenderPhotoProps

### ISSUE THREAD

**Issue by rolanday** [igordanchenko/react-photo-album#91]
### Describe the bug

AFAICT, type `PhotoProps` should be `RenderPhotoProps` under Next.js 13 example:

https://react-photo-album.com/examples/nextjs:

```
const NextJsImage: React.FC<PhotoProps> = ({
    imageProps: { src, alt, title, sizes, className, onClick },
    wrapperStyle,
}) => (
```

Also, I intend to pass add'l props to the custom render function (e.g., a badge overlay), but am hitting typescript friction -- shouldn't be so difficult and I'm prob in the weeds. Do you have any suggestions on how to best accomplish?

Thanks!!

-Roland.

### Expected behavior

Doc bug -- see description.

### How to reproduce

Read docs.

**Comment by igordanchenko** [comment]
Thank you for catching this error. `PhotoProps` type was renamed to `RenderPhotoProps` in 2.0.0. I'll go ahead and update the documentation.

**Comment by igordanchenko** [comment]
> Also, I intend to pass add'l props to the custom render function (e.g., a badge overlay), but am hitting typescript friction -- shouldn't be so difficult and I'm prob in the weeds. Do you have any suggestions on how to best accomplish?

I'm assuming your additional props are coming in the `photos` array. In that case you can use one of the following approaches to access custom photo attributes and keep TypeScript happy.

1) Use inline render function.

```jsx
const photos = [
  { 
    src: ... ,
    width: ... ,
    height: ... ,
    badge: ...  // <-- custom attribute
  }
];

// ...

<PhotoAlbum
  photos={photos}
  renderPhoto={({ photo: { badge } }) => {
    // ...
  }}
/>
```

2) Extend `Photo` interface.

```jsx
import * as React from "react";
import PhotoAlbum, { Photo, RenderPhotoProps } from "react-photo-album";

interface CustomPhoto extends Photo {
    badge?: React.ReactNode;
}

const NextJsImage: React.FC<RenderPhotoProps<CustomPhoto>> = ({
    photo: { badge }
}) => {
    // ...
};
```

3) Use global augmentation.

Save the following `react-photo-album.d.ts` file under your project root or `types` folder.

```ts
// react-photo-album.d.ts

import * as React from "react";

declare module "react-photo-album" {
    interface Photo extends Photo {
        badge?: React.ReactNode;
    }
}

export {};
```

```jsx
import * as React from "react";
import PhotoAlbum, { RenderPhotoProps } from "react-photo-album";

const NextJsImage: React.FC<RenderPhotoProps> = ({
    photo: { badge }
}) => {
    // ...
};
```

**Comment by rolanday** [comment]
Works like a charm. You saved me a lot of time, I'm sure. Thank you so much!!
