### ISSUE TITLE
Prevent small images from scaling up

### ISSUE THREAD

**Issue by dawi** [igordanchenko/react-photo-album#99]
### Is your feature request related to a problem? Please describe.

I have recognized that small images are scaled up.

As far as I can see, this cannot be solved by using a custom renderPhoto function, because the distribution of photos to rows is done before.

It would be great if this library would support that.

### Describe the solution you'd like

Small images should not exceed their original size.

Use a small image (50 x 50 px) in the Photo-Array.

**Comment by igordanchenko** [comment]
Hi Daniel, 

Thank you for bringing this up. I'd like to understand your use case better. Can you provide me with an example? (a screenshot or a code sandbox would be great)

Have you tried adjusting your `targetRowHeight` based on the dimensions of your smallest image?

What would be your desired solution at the library level?

**Comment by dawi** [comment]
Hi Igor,

yes I have created a small code sandbox example: https://codesandbox.io/s/lucid-merkle-wlkrk3

I have uploaded a small logo there to demonstrate the issue.

In this example I have set the `maxWidth` and `maxHeight` attribute to prevent the image to scale up.

```tsx
<img
  alt={alt}
  style={{
    ...style,
    width: "100%",
    border: "1px solid black",
    maxWidth: photo.width,
    maxHeight: photo.height
  }}
  {...restImageProps}
/>
```

However this does not prevent the space being taken in the row.

**Comment by igordanchenko** [comment]
Thank you for sharing the example. So, in this case, you are telling the library that you want your rows to be approximately 300px high. But since one of your images is just 111px high, it's almost guaranteed to be scaled up in most cases. 

Have you considered modifying the `targetRowHeight`? For example, you can limit the `targetRowHeight` to the height of your smallest image.

```js
targetRowHeight={Math.min(...[300, ...photos.map(({ height }) => height)])}
```
or 
```js
targetRowHeight={Math.min(...[300, ...photos.map(({ height }) => 0.9 * height)])}
```

I put together a demo demonstrating this approach: https://codesandbox.io/s/react-photo-album-99-h9dhh8?file=/src/App.tsx

Does this look like the solution you are looking for?

**Comment by igordanchenko** [comment]
Can you describe how you expect the library to handle this case?

**Comment by dawi** [comment]
Yes. For my use-case it would be sufficient if I could configure images to never scale up and that the wrapper div does not get wider then the contained image.

I have made a scribble as example:

<img width="1320" alt="scribble-of-the-desired-bahvior" src="https://user-images.githubusercontent.com/129870/213190122-d02b2c24-7d3d-41eb-99fc-edced05aaec1.png">

**Comment by igordanchenko** [comment]
Daniel, thank you for providing the visual aid; it was very helpful. Unfortunately, what you are asking for is very different from the layout algorithm this library uses, and I do not see a reasonable approach to accommodate your desired implementation within the scope of this library. However, if you have an algorithm in mind, you can patch this library with `patch-package` and completely replace the current algorithm [here](https://github.com/igordanchenko/react-photo-album/blob/499802e4005265d095a294b2884a84f494cd9ba8/src/components/layouts/RowsLayout.tsx#L19).

I'll go ahead and close this ticket, but please feel free to reach out if you think of alternative ways to address your use case.

**Comment by dawi** [comment]
Ok, sad to hear. I think it would be a valuable addition to this library.
